/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CowService } from "../cow.service";
import { CowCreateInput } from "./CowCreateInput";
import { Cow } from "./Cow";
import { CowFindManyArgs } from "./CowFindManyArgs";
import { CowWhereUniqueInput } from "./CowWhereUniqueInput";
import { CowUpdateInput } from "./CowUpdateInput";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { TransactionWhereUniqueInput } from "../../transaction/base/TransactionWhereUniqueInput";

export class CowControllerBase {
  constructor(protected readonly service: CowService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Cow })
  async createCow(@common.Body() data: CowCreateInput): Promise<Cow> {
    return await this.service.createCow({
      data: data,
      select: {
        age: true,
        breed: true,
        createdAt: true,
        id: true,
        name: true,
        price: true,
        updatedAt: true,
        weight: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Cow] })
  @ApiNestedQuery(CowFindManyArgs)
  async cows(@common.Req() request: Request): Promise<Cow[]> {
    const args = plainToClass(CowFindManyArgs, request.query);
    return this.service.cows({
      ...args,
      select: {
        age: true,
        breed: true,
        createdAt: true,
        id: true,
        name: true,
        price: true,
        updatedAt: true,
        weight: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Cow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async cow(@common.Param() params: CowWhereUniqueInput): Promise<Cow | null> {
    const result = await this.service.cow({
      where: params,
      select: {
        age: true,
        breed: true,
        createdAt: true,
        id: true,
        name: true,
        price: true,
        updatedAt: true,
        weight: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Cow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCow(
    @common.Param() params: CowWhereUniqueInput,
    @common.Body() data: CowUpdateInput
  ): Promise<Cow | null> {
    try {
      return await this.service.updateCow({
        where: params,
        data: data,
        select: {
          age: true,
          breed: true,
          createdAt: true,
          id: true,
          name: true,
          price: true,
          updatedAt: true,
          weight: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Cow })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCow(
    @common.Param() params: CowWhereUniqueInput
  ): Promise<Cow | null> {
    try {
      return await this.service.deleteCow({
        where: params,
        select: {
          age: true,
          breed: true,
          createdAt: true,
          id: true,
          name: true,
          price: true,
          updatedAt: true,
          weight: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/transactions")
  @ApiNestedQuery(TransactionFindManyArgs)
  async findTransactions(
    @common.Req() request: Request,
    @common.Param() params: CowWhereUniqueInput
  ): Promise<Transaction[]> {
    const query = plainToClass(TransactionFindManyArgs, request.query);
    const results = await this.service.findTransactions(params.id, {
      ...query,
      select: {
        amount: true,

        buyer: {
          select: {
            id: true,
          },
        },

        cow: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        date: true,
        id: true,

        seller: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/transactions")
  async connectTransactions(
    @common.Param() params: CowWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        connect: body,
      },
    };
    await this.service.updateCow({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/transactions")
  async updateTransactions(
    @common.Param() params: CowWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        set: body,
      },
    };
    await this.service.updateCow({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/transactions")
  async disconnectTransactions(
    @common.Param() params: CowWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        disconnect: body,
      },
    };
    await this.service.updateCow({
      where: params,
      data,
      select: { id: true },
    });
  }
}
